const JobData = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "Google",
    location: "Remote",
    category: "tech",
    description:
      "Build and maintain modern web interfaces using React and TypeScript.",
    postedDate: "2025-06-01",
  },
  {
    id: 2,
    title: "Marketing Manager",
    company: "Coca-Cola",
    location: "Mumbai",
    category: "marketing",
    description:
      "Lead marketing campaigns and brand strategy for the Indian market.",
    postedDate: "2025-05-28",
  },
  {
    id: 3,
    title: "Data Analyst",
    company: "TCS",
    location: "Bangalore",
    category: "finance",
    description:
      "Analyze financial trends and generate reports for stakeholders.",
    postedDate: "2025-06-05",
  },
  {
    id: 4,
    title: "Full Stack Developer",
    company: "Amazon",
    location: "Hyderabad",
    category: "tech",
    description:
      "Develop and maintain scalable full-stack applications with Node.js and React.",
    postedDate: "2025-06-03",
  },
  {
    id: 5,
    title: "Social Media Specialist",
    company: "Zomato",
    location: "Delhi",
    category: "marketing",
    description:
      "Manage content and ad strategy across all social media platforms.",
    postedDate: "2025-06-06",
  },
  {
    id: 6,
    title: "Investment Advisor",
    company: "HDFC Bank",
    location: "Chennai",
    category: "finance",
    description:
      "Provide investment guidance to clients and manage portfolios.",
    postedDate: "2025-05-30",
  },
  {
    id: 7,
    title: "Backend Engineer",
    company: "Microsoft",
    location: "Bangalore",
    category: "tech",
    description: "Build scalable backend services using .NET and Azure.",
    postedDate: "2025-06-02",
  },
  {
    id: 8,
    title: "Content Strategist",
    company: "Netflix",
    location: "Mumbai",
    category: "marketing",
    description: "Design and execute content strategies for streaming media.",
    postedDate: "2025-06-04",
  },
  {
    id: 9,
    title: "Credit Analyst",
    company: "ICICI Bank",
    location: "Pune",
    category: "finance",
    description:
      "Assess credit data and financial statements of individuals and firms.",
    postedDate: "2025-06-01",
  },
  {
    id: 10,
    title: "UI/UX Designer",
    company: "Adobe",
    location: "Remote",
    category: "tech",
    description: "Design modern UI experiences and conduct usability testing.",
    postedDate: "2025-05-31",
  },
  {
    id: 11,
    title: "Digital Marketing Executive",
    company: "PepsiCo",
    location: "Kolkata",
    category: "marketing",
    description: "Run digital ad campaigns and SEO strategies.",
    postedDate: "2025-06-07",
  },
  {
    id: 12,
    title: "Risk Manager",
    company: "Axis Bank",
    location: "Mumbai",
    category: "finance",
    description: "Develop and monitor risk policies and procedures.",
    postedDate: "2025-05-29",
  },
  {
    id: 13,
    title: "Machine Learning Engineer",
    company: "NVIDIA",
    location: "Bangalore",
    category: "tech",
    description: "Build and optimize ML models for real-time applications.",
    postedDate: "2025-06-01",
  },
  {
    id: 14,
    title: "PR Manager",
    company: "Sony",
    location: "Delhi",
    category: "marketing",
    description: "Coordinate media and public relations efforts.",
    postedDate: "2025-05-30",
  },
  {
    id: 15,
    title: "Financial Analyst",
    company: "Deloitte",
    location: "Hyderabad",
    category: "finance",
    description: "Interpret financial data and assist in budgeting processes.",
    postedDate: "2025-06-06",
  },
  {
    id: 16,
    title: "DevOps Engineer",
    company: "Infosys",
    location: "Chennai",
    category: "tech",
    description: "Maintain CI/CD pipelines and automate deployments.",
    postedDate: "2025-06-02",
  },
  {
    id: 17,
    title: "Email Marketing Specialist",
    company: "Swiggy",
    location: "Gurgaon",
    category: "marketing",
    description: "Plan and execute email campaigns to boost user retention.",
    postedDate: "2025-06-03",
  },
  {
    id: 18,
    title: "Auditor",
    company: "KPMG",
    location: "Ahmedabad",
    category: "finance",
    description:
      "Conduct audits and ensure compliance with financial regulations.",
    postedDate: "2025-06-05",
  },
  {
    id: 19,
    title: "React Native Developer",
    company: "Ola",
    location: "Bangalore",
    category: "tech",
    description: "Create cross-platform mobile apps using React Native.",
    postedDate: "2025-05-28",
  },
  {
    id: 20,
    title: "Brand Manager",
    company: "Nestlé",
    location: "Pune",
    category: "marketing",
    description: "Oversee branding efforts and product positioning.",
    postedDate: "2025-06-04",
  },
];

export default JobData;
